feat: automatically generate Django secret
The Django secret should *always* be a strong secret value, and because
the user should never need to enter it directly, we should automatically
generate it for them to ensure it is strong. As a reminder, the Django
secret is never used for login; it is used for cryptographic operations.

This change adds a prompt to ask if the script should automatically
generate the secret, and this option can automatically be selected by
specifying the '-y' flag upon run.

This also fixes at least two ShellCheck notices:

* https://www.shellcheck.net/wiki/SC2162
* https://www.shellcheck.net/wiki/SC2059

diff --git a/bin/create-app-secret b/bin/create-app-secret
--- a/bin/create-app-secret
+++ b/bin/create-app-secret
@@ -1,17 +1,57 @@
 #!/bin/bash
-read -s -p "Enter the Discovery Django secret key: " discovery_django_secret_key
-echo
-if [ -z "${discovery_django_secret_key}" ]; then
-  echo "The Discovery Django secret key cannot be empty."
-  exit 1
-fi
-read -s -p "Re-enter the secret key: " discovery_django_secret_key2
-echo
-if [ ! "${discovery_django_secret_key}" = "${discovery_django_secret_key2}" ]; then
-  echo "Discovery Django secret keys do not match."
-  exit 1
-fi
 
-podman secret rm discovery-django-secret-key >/dev/null 2>&1
-printf "${discovery_django_secret_key}" | podman secret create discovery-django-secret-key -
-podman secret ls --filter name=discovery-django-secret-key
+function set_django_secret_key {
+  podman secret rm discovery-django-secret-key >/dev/null 2>&1
+  printf '%s' "$1" | podman secret create discovery-django-secret-key -
+  podman secret ls --filter name=discovery-django-secret-key
+}
+
+function generate_key {
+  local discovery_django_secret_key
+  discovery_django_secret_key=$(head -c 64 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9')
+  set_django_secret_key "${discovery_django_secret_key}"
+}
+
+function prompt_key {
+  local discovery_django_secret_key
+  read -srp "Enter the Discovery Django secret key: " discovery_django_secret_key
+  echo
+  if [ -z "${discovery_django_secret_key}" ]; then
+    echo "The Discovery Django secret key cannot be empty."
+    exit 1
+  fi
+  read -srp "Re-enter the secret key: " discovery_django_secret_key2
+  echo
+  if [ ! "${discovery_django_secret_key}" = "${discovery_django_secret_key2}" ]; then
+    echo "Discovery Django secret keys do not match."
+    exit 1
+  fi
+  set_django_secret_key "${discovery_django_secret_key}"
+}
+
+function prompt_for_generation {
+  while true; do
+    read -rp "Automatically generate new Django secret key? [y/n]: " yn
+    case $yn in
+    [Yy]*)
+      generate_key
+      exit
+      ;;
+    [Nn]*)
+      prompt_key
+      exit
+      ;;
+    esac
+  done
+}
+
+while getopts "Yy" opt; do
+  case $opt in
+  [Yy])
+    generate_key
+    exit
+    ;;
+  *) ;;
+  esac
+done
+prompt_for_generation
