fix(rpm): Updated create-app-secret script to be usable for production too.
- Updated the create-app-secret script to not default to development as
  it can be used for production too. Script now checks for empty inputs
  and prompts the user a second time for verification before creating
  the podman secret.

- Updated the NOTES.md file to include the Quadlet References we had
  in the old README.md

diff --git a/bin/create-app-secret b/bin/create-app-secret
--- a/bin/create-app-secret
+++ b/bin/create-app-secret
@@ -1,8 +1,15 @@
 #!/bin/bash
-read -s -p "Enter the Discovery Django secret key (development): " discovery_django_secret_key
+read -s -p "Enter the Discovery Django secret key: " discovery_django_secret_key
 echo
 if [ -z "${discovery_django_secret_key}" ]; then
-  discovery_django_secret_key="development"
+  echo "The Discovery Django secret key cannot be empty."
+  exit 1
+fi
+read -s -p "Re-enter the secret key: " discovery_django_secret_key2
+echo
+if [ ! "${discovery_django_secret_key}" = "${discovery_django_secret_key2}" ]; then
+  echo "Discovery Django secret keys do not match."
+  exit 1
 fi
 
 podman secret rm discovery-django-secret-key >/dev/null 2>&1
