refactor: clean up installer script
General cleanups include:

* send error messages to stderr
* be more POSIX compliant
* use `XDG_` variables if present
* encapsulate logic better in functions
* use more consistent variable names
* be more deliberate with program argument parsing
* add inline comments describing function arguments
* `set -e` to halt upon unexpected failures

diff --git a/bin/create-server-password b/bin/create-server-password
--- a/bin/create-server-password
+++ b/bin/create-server-password
@@ -1,17 +1,19 @@
 #!/bin/bash
+set -e
+
 read -srp "Enter the new Quipucords server password: " dsc_pass
 echo
 read -srp "Re-enter the password: " dsc_pass2
 echo
 if [ ! "${dsc_pass}" = "${dsc_pass2}" ]; then
-  echo "Passwords do not match."
+  echo "Passwords do not match." 1>&2
   exit 1
 fi
-[[ ${#dsc_pass} -lt 10 ]] && echo "Password must be at least 10 characters long." && exit 1
-! [[ "${dsc_pass}" =~ [a-zA-Z] ]] && echo "Password must contain at least one alpha character." && exit 1
+[[ ${#dsc_pass} -lt 10 ]] && echo "Password must be at least 10 characters long." 1>&2 && exit 1
+! [[ "${dsc_pass}" =~ [a-zA-Z] ]] && echo "Password must contain at least one alpha character." 1>&2 && exit 1
 for bad_pass in "dscpassw0rd" "qpcpassw0rd"; do
-  [[ "${dsc_pass}" == "${bad_pass}" ]] && echo "Password cannot be ${bad_pass}" && exit 1
+  [[ "${dsc_pass}" == "${bad_pass}" ]] && echo "Password cannot be ${bad_pass}" 1>&2 && exit 1
 done
-podman secret rm quipucords-server-password >/dev/null 2>&1
+podman secret rm quipucords-server-password >/dev/null 2>&1 || true
 printf '%s' "${dsc_pass}" | podman secret create quipucords-server-password -
 podman secret ls --filter name=quipucords-server-password
