feat(rpm): Added server password validation
- Added server password restriction checks.
  - password must be at least 10 characters long
  - password must include at least one letter a-z A-Z
  - password cannot be dscpassw0rd or qpcpassw0rd

diff --git a/bin/create-server-password b/bin/create-server-password
--- a/bin/create-server-password
+++ b/bin/create-server-password
@@ -7,6 +7,12 @@ if [ ! "${dsc_pass}" = "${dsc_pass2}" ]; then
   echo "Passwords do not match."
   exit 1
 fi
+[[ ${#dsc_pass} -lt 10 ]] && echo "Password must be at least 10 characters long." && exit 1
+! [[ "${dsc_pass}" =~ [a-zA-Z] ]] && echo "Password must contain at least one alpha character." && exit 1
+for bad_pass in "dscpassw0rd" "qpcpassw0rd"
+do
+  [[ "${dsc_pass}" == "${bad_pass}" ]] && echo "Password cannot be ${bad_pass}" && exit 1
+done
 podman secret rm discovery-server-password >/dev/null 2>&1
 printf "${dsc_pass}" | podman secret create discovery-server-password -
 podman secret ls --filter name=discovery-server-password
